let g:jedi#goto_command = "<leader>Jd"
let g:jedi#goto_assignments_command = "<leader>Jg"
let g:jedi#goto_definitions_command = ""
let g:jedi#documentation_command = "JK"
let g:jedi#usages_command = "<leader>Jn"
let g:jedi#completions_command = "<leader>Jc"
let g:jedi#rename_command = "<leader>Jr"
