---
- hosts: all
  sudo: yes
  tasks:
  - name: install base development packages
    apt: name={{item}} state=present update_cache=yes
    with_items:
      - python-pip
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - python-dev
      - wget
      - curl
      - llvm
      - libncurses5-dev
      - cmake
      - exuberant-ctags
  - name: Install applications
    apt: name={{item}} state=present
    with_items:
      - silversearcher-ag
      - httpie
      - git
      - mercurial
  - name: Clone dotfiles repo
    git: repo=git://github.com/msull/dotfiles.git dest=/home/vagrant/dotfiles
    become: yes
    become_user: vagrant
    ignore_errors: yes
  - name: Sync dotfiles
    command: /home/vagrant/dotfiles/sync.sh
    become: yes
    become_user: vagrant
  - name: Add public keys
    authorized_key:
      user: vagrant
      key: https://www.github.com/msull.keys
      manage_dir: no
  - name: Make /python directory
    file: path=/python state=directory owner=vagrant group=vagrant
  - name: Clone pyenv repo
    git: repo=https://www.github.com/yyuu/pyenv.git dest=/python
    become: yes
    become_user: vagrant
  - name: Get PyENV Installer
    get_url: url=https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer dest=/python/installer.sh mode=0755
  - name: Install pyenv
    command: /python/installer.sh
    become: yes
    become_user: vagrant
    environment:
      PYENV_ROOT: /python
  - name: Install Python 2.7.11
    shell: '/python/libexec/pyenv install 2.7.11'
    become: yes
    become_user: vagrant
    ignore_errors: yes
    environment:
      PYENV_ROOT: /python
  - name: Install Python 3.5.1
    shell: '/python/libexec/pyenv install 3.5.1'
    become: yes
    become_user: vagrant
    ignore_errors: yes
    environment:
      PYENV_ROOT: /python
  - name: Set python 3.5.1 as default
    shell: '/python/libexec/pyenv global 3.5.1'
    become: yes
    become_user: vagrant
    ignore_errors: yes
    environment:
      PYENV_ROOT: /python
  - name: Get NodeJS Repo installer
    get_url: url=https://deb.nodesource.com/setup_5.x dest=/tmp/nodejsinstaller.sh mode=0755
  - name: Execute NodeJS Repo installer
    command: /tmp/nodejsinstaller.sh
  - name: Install NodeJS
    apt: name=nodejs state=present
  - name: Update global Node.js packages
    npm: name={{item}} global=yes
    with_items:
      - npm
      - learnyounode
      - typescript
      - jshint
  - name: Build youcompleteme
    command: /python/versions/2.7.11/bin/python /home/vagrant/.vim_plugins/youcompleteme/install.py --tern-completer
    environment:
      YCM_CORES: 1
