# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
if [ -e /python/libexec/pyenv ]; then
	export PYENV_ROOT=/python
	/python/libexec/pyenv global system
fi
SCRIPT


Vagrant.configure(2) do |config|
    config.vm.define "devmachine" do |virt|
        virt.vm.hostname = "devmachine"
        virt.vm.box = "ubuntu/trusty64"
        virt.vm.network "private_network", type: "dhcp"
        virt.ssh.forward_agent = true
        virt.vm.network "forwarded_port", guest: 3000, host: 3000
        virt.vm.network "forwarded_port", guest: 5000, host: 5000
        virt.vm.network "forwarded_port", guest: 8000, host: 8000
        virt.vm.network "forwarded_port", guest: 8080, host: 8080
        virt.vm.network "forwarded_port", guest: 8888, host: 8888
        virt.vm.provision "shell", inline: $script
        virt.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "/vagrant/playbook.yml"
        end
        if File.directory?(File.expand_path("~/workspace"))
            virt.vm.synced_folder "~/workspace", "/home/vagrant/workspace", nfs: true
        end

        virt.vm.provider :virtualbox do |vb|
            vb.name = "devbox"
            vb.memory = 1024
            vb.cpus = 2
            vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
            vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        end
    end
end
