# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
if [ -e /python/libexec/pyenv ]; then
	export PYENV_ROOT=/python
	/python/libexec/pyenv global system
fi
SCRIPT


Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.provision "shell", inline: $script
    config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "/vagrant/playbook.yml"
    end
    
    config.vm.provider :virtualbox do |vb|
	  vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
	  vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
	end
    
end
