output-format: json

strictness: high
test-warnings: true
doc-warnings: false

#inherits:
  #- my/other/profile.yml

ignore-paths:
  - docs

ignore-patterns:
  - (^|/)skip(this)?(/|$)

pep8:
  disable:
    - W602
    - W603
  enable:
    - W601
  options:
    max-line-length: 100

mccabe:
  run: true
